{{- if eq .Values.database.type "internal" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.database.internal.image.repository }}:{{ .Values.database.internal.image.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.database.internal.port }}
          envFrom:
            - configMapRef:
                name: postgresql-config
          volumeMounts:
            - mountPath: /var/lib/postgresqlql/data
              name: postgresql-volume
      volumes:
        - name: postgresql-volume
          persistentVolumeClaim:
            claimName: postgresql-pvc
{{- end -}}
