{{- if .Values.registryCredentials.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-secret.name" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
