apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concord-agent-operator
  template:
    metadata:
      labels:
        name: concord-agent-operator
    spec:
      serviceAccountName: concord-agent-operator
      {{- include "imagePullSecretName" . | nindent 6 }}
      containers:
        - name: concord-agent-operator
          {{- if .Values.agentOperatorImageOverride }}
          image: {{ .Values.agentOperatorImageOverride }}
          {{- else }}
          image: {{ .Values.registry }}/{{ .Values.agentOperatorImageName }}:{{ .Values.version }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SCALE_UP_DELAY_MS
              value: "15000"
            - name: SCALE_DOWN_DELAY_MS
              value: "180000"
            - name: INCREMENT_PERCENTAGE
              value: "50"
            - name: DECREMENT_PERCENTAGE
              value: "10"
            - name: INCREMENT_THRESHOLD_FACTOR
              value: "1.5"
            - name: DECREMENT_THRESHOLD_FACTOR
              value: "1.0"
            - name: OPERATOR_NAME
              value: "concord-agent-operator"
            - name: CONCORD_BASE_URL
              value: "http://concord-server:{{ .Values.expose.port }}"
            - name: CONCORD_API_TOKEN
              value: {{ .Values.server.adminToken }}
